config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "calendar#index"

  resources :calendar, only: %i[index]

  resources :reminders, only: %i[new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reminder_record.rb
class ReminderRecord < ApplicationRecord
  self.table_name = :reminders

  validates :reminder_time, presence: true, comparison: { greater_than: -> { DateTime.current } }
  validates :text, presence: true
  validates :recipient_email, presence: true

  scope :not_sent, -> { where(sent_at: nil) }

  def start_time
    reminder_time
  end

  def has_been_sent?
    sent_at.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    reminders = ReminderRecord.where(reminder_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)

    respond_to do |f|
      f.html { render :index, locals: { reminders: } }
    end
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def new
    reminder = ReminderRecord.new

    respond_to do |f|
      f.html { render :new, locals: { reminder: } }
    end
  end

  def create
    permitted = params.require(:reminder).permit(:text, :reminder_time, :recipient_email)

    reminder = ReminderRecord.new(permitted)

    if reminder.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity, locals: { reminder: }
    end
  end

  def show
    reminder = ReminderRecord.find(params[:id])

    respond_to do |f|
      f.html { render :show, locals: { reminder: } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendar/index.html.erb
<%= link_to "Создать напоминание", new_reminder_path, class: "underline text-blue-500" %>

<%= month_calendar(events: reminders) do |date, reminders| %>
  <%= date.day %>

  <div class="flex flex-col">
    <% reminders.each do |reminder| %>
      <%= link_to reminder.reminder_time.strftime("%H:%M"),
        reminder_path(reminder),
        class: "underline text-blue-500 w-max mx-auto"
      %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Reminder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="mx-auto container">
    <%= yield %>
  </body>
</html>

app/views/reminders/new.html.erb
<% if reminder.errors.present? %>
  <ul class="bg-red-200">
    <% reminder.errors.full_messages.each do |err_msg| %>
      <li><%= err_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :reminder, url: reminders_path, class: "flex flex-col gap-2" do |f| %>
  <%= label_tag :reminder_time, "Напомнить в" %>
  <%= f.datetime_field :reminder_time %>
  <%= label_tag :recipient_email, "Email получателя" %>
  <%= f.email_field :recipient_email %>
  <%= label_tag :text, "Текст" %>
  <%= f.text_area :text %>

  <%= f.submit "Создать Напоминание" %>
<% end %>

app/views/reminders/show.html.erb
<div>
  <p>
    id: <%= reminder.id %>
  </p>
  <p>
    text: <%= reminder.text %>
  </p>
</div>